from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol

from .commands import Action, Command, command_help_lines


class SystemController(Protocol):
    def open_app(self, app_name: str) -> str: ...
    def close_app(self, app_name: str) -> str: ...
    def open_notepad(self) -> None: ...
    def open_calculator(self) -> None: ...
    def volume_up(self) -> None: ...
    def volume_down(self) -> None: ...
    def volume_mute(self) -> None: ...
    def set_volume(self, percent: int) -> None: ...
    def media_play_pause(self) -> None: ...
    def media_next(self) -> None: ...
    def media_previous(self) -> None: ...
    def media_stop(self) -> None: ...
    def show_desktop(self) -> None: ...
    def minimize_window(self) -> None: ...
    def maximize_window(self) -> None: ...
    def switch_window(self) -> None: ...
    def screenshot(self) -> None: ...
    def browser_back(self) -> None: ...
    def browser_forward(self) -> None: ...
    def scroll_up(self) -> None: ...
    def scroll_down(self) -> None: ...
    def copy(self) -> None: ...
    def cut(self) -> None: ...
    def paste(self) -> None: ...
    def undo(self) -> None: ...
    def redo(self) -> None: ...
    def select_all(self) -> None: ...
    def new_tab(self) -> None: ...
    def close_tab(self) -> None: ...
    def reopen_tab(self) -> None: ...
    def refresh(self) -> None: ...
    def zoom_in(self) -> None: ...
    def zoom_out(self) -> None: ...
    def zoom_reset(self) -> None: ...
    def press_enter(self) -> None: ...
    def press_escape(self) -> None: ...
    def close_window(self) -> None: ...


@dataclass(frozen=True)
class ExecutionResult:
    message: str
    should_quit: bool = False


class CommandExecutor:
    """Execute validated commands received from the authorized Telegram chat."""

    def __init__(self, controller: SystemController) -> None:
        self.controller = controller

    def execute(self, command: Command) -> ExecutionResult:
        if command.action is Action.OPEN_APP:
            if not command.argument:
                return ExecutionResult("No application name was supplied.")
            app_name = self.controller.open_app(command.argument)
            return ExecutionResult(f"Opening {app_name}")
        if command.action is Action.CLOSE_APP:
            if not command.argument:
                return ExecutionResult("No application name was supplied.")
            app_name = self.controller.close_app(command.argument)
            return ExecutionResult(f"Closing {app_name}")
        if command.action is Action.SET_VOLUME:
            percent = int(command.argument or "0")
            self.controller.set_volume(percent)
            return ExecutionResult(f"Volume set to {percent}%")

        handlers = {
            Action.OPEN_NOTEPAD: (self.controller.open_notepad, "Opening Notepad"),
            Action.OPEN_CALCULATOR: (self.controller.open_calculator, "Opening Calculator"),
            Action.VOLUME_UP: (self.controller.volume_up, "Volume up"),
            Action.VOLUME_DOWN: (self.controller.volume_down, "Volume down"),
            Action.VOLUME_MUTE: (self.controller.volume_mute, "Toggled mute"),
            Action.MEDIA_PLAY_PAUSE: (self.controller.media_play_pause, "Toggled play/pause"),
            Action.MEDIA_NEXT: (self.controller.media_next, "Next song"),
            Action.MEDIA_PREVIOUS: (self.controller.media_previous, "Previous song"),
            Action.MEDIA_STOP: (self.controller.media_stop, "Stopped playback"),
            Action.SHOW_DESKTOP: (self.controller.show_desktop, "Showing desktop"),
            Action.MINIMIZE_WINDOW: (self.controller.minimize_window, "Minimized window"),
            Action.MAXIMIZE_WINDOW: (self.controller.maximize_window, "Maximized window"),
            Action.SWITCH_WINDOW: (self.controller.switch_window, "Switched window"),
            Action.SCREENSHOT: (self.controller.screenshot, "Screenshot copied to clipboard"),
            Action.BROWSER_BACK: (self.controller.browser_back, "Browser back"),
            Action.BROWSER_FORWARD: (self.controller.browser_forward, "Browser forward"),
            Action.SCROLL_UP: (self.controller.scroll_up, "Scrolled up"),
            Action.SCROLL_DOWN: (self.controller.scroll_down, "Scrolled down"),
            Action.COPY: (self.controller.copy, "Copied"),
            Action.CUT: (self.controller.cut, "Cut"),
            Action.PASTE: (self.controller.paste, "Pasted"),
            Action.UNDO: (self.controller.undo, "Undo"),
            Action.REDO: (self.controller.redo, "Redo"),
            Action.SELECT_ALL: (self.controller.select_all, "Selected all"),
            Action.NEW_TAB: (self.controller.new_tab, "Opened a new tab"),
            Action.CLOSE_TAB: (self.controller.close_tab, "Closed the tab"),
            Action.REOPEN_TAB: (self.controller.reopen_tab, "Reopened the closed tab"),
            Action.REFRESH: (self.controller.refresh, "Refreshed"),
            Action.ZOOM_IN: (self.controller.zoom_in, "Zoomed in"),
            Action.ZOOM_OUT: (self.controller.zoom_out, "Zoomed out"),
            Action.ZOOM_RESET: (self.controller.zoom_reset, "Reset zoom"),
            Action.PRESS_ENTER: (self.controller.press_enter, "Pressed Enter"),
            Action.PRESS_ESCAPE: (self.controller.press_escape, "Pressed Escape"),
            Action.CLOSE_WINDOW: (self.controller.close_window, "Closed the window"),
        }

        if command.action is Action.SHOW_HELP:
            return ExecutionResult("Supported commands:\n  " + "\n  ".join(command_help_lines()))
        if command.action is Action.QUIT:
            return ExecutionResult("Stopping Remote control", should_quit=True)

        handler, message = handlers[command.action]
        handler()
        return ExecutionResult(message)
